<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\PicSerialSplash256.ico</ApplicationIcon>
    <PackageIcon>PicSerialSplash256.ico</PackageIcon>
    <EnableNETAnalyzers>False</EnableNETAnalyzers>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="PicSerialSplash.png" />
    <None Remove="PicSerialSplash1.png" />
    <None Remove="PicSrial.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\PicSerialSplash256.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MahApps.Metro.IconPacks" Version="6.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="PicSerialSplash.png" />
    <Resource Include="PicSerialSplash1.png" />
    <Resource Include="PicSrial.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\PicSerialSplash256.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
